### ISSUE TITLE
Allow controller option for avModal

### ISSUE THREAD

**Issue by bobbennett** [Availity/availity-angular#139]
We need to add the ability to supply a controller to avModal

**Comment by robmcguinness** [comment]
purpose?  just curious :smirk_cat:

**Comment by bobbennett** [comment]
It'll allow you to make more modular code. You don't have to worry about creating a new scope and setting all of its properties each time you want a modal. It also provides a more familiar option set to other angular components and libraries like directives and ui-router. 

AngularUI has a nice set of options: http://angular-ui.github.io/bootstrap/#/modal. Here's the controller option implementation: https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L639. It also allows use of the controllerAs and bindToController options.

**Comment by robmcguinness** [comment]
ok sounds fair

**Comment by robmcguinness** [comment]
@bobbennett was this resolved with the recently added controller as syntax?

**Comment by bobbennett** [comment]
Yeah that's exactly what was needed

**Comment by robmcguinness** [comment]
ok this can be closed then.

**Comment by bobbennett** [comment]
Closed by #197
