### ISSUE TITLE
upgrade to Angular 1.5

### ISSUE THREAD

**Issue by bobbennett** [Availity/availity-angular#146]
Angular 1.3+ drops support for IE8

**Comment by robmcguinness** [comment]
* https://github.com/Availity/availity-angular/commit/c051963827278d2f58eb128306a2fbfa4f64f0b4
* https://github.com/Availity/availity-angular/commit/8f0eda454079db3d5cc299a268d4bb62abff2242

**Comment by JamieCrisman** [comment]
<3

**Comment by robmcguinness** [comment]
we are targeting Angular v1.5 now 🐹

**Comment by JamieCrisman** [comment]
🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰

**Comment by robmcguinness** [comment]
Angular 1.6 🔥 updates are ready
