### ISSUE TITLE
Validation Field Not Updating After Fixing Validation Error

### ISSUE THREAD

**Issue by WilliamFayette** [Availity/availity-angular#147]
![image](https://cloud.githubusercontent.com/assets/14983950/10289754/0f1078b6-6b6e-11e5-9e2f-1548c67352ee.png)
![image](https://cloud.githubusercontent.com/assets/14983950/10289762/1b22ef4e-6b6e-11e5-8e36-6e9f99553e69.png)
![image](https://cloud.githubusercontent.com/assets/14983950/10289770/23d0229c-6b6e-11e5-8670-1d83362e57cc.png)

``` javascript
    'amount': {
      'required': {
        'message': 'Amount is required.'
      }
    },
```

**Comment by robmcguinness** [comment]
can you show the markup used as well?

**Comment by WilliamFayette** [comment]
```javascript
<div class="form-group">
                <label for="creditCardNumberInput">Credit Card</label>
                <input class="form-control" id="creditCardNumberInput" data-ng-model="vm.paymentInformation.creditCardNumber" data-av-val-field="creditCardNumber"/>
                <p id="creditCardNumberValidationMessage" data-av-val-container></p>
              </div>
```

**Comment by taylornturner** [comment]
Can we capitalize the "R" in Required to match the capital "O" in Optional as per the uikit? http://availity.github.io/availity-uikit/components.html#OptionalFormInputs

**Comment by WilliamFayette** [comment]
<div class="form-group">
    <label for="creditCardNumberInput">Credit Card
     <small>(Required)</small>
    </label>
    <input class="form-control" id="creditCardNumberInput" data-ng-model="vm.paymentInformation.creditCardNumber" data-av-val-field="creditCardNumber"/>
    <p id="creditCardNumberValidationMessage" data-av-val-container></p>
</div>

**Comment by robmcguinness** [comment]
@taylornturner that is controlled by the app developer.
