### ISSUE TITLE
Popover position incorrect on page load

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#153]
When using the new feature `options.showOnLoad` the popover is positioned incorrectly on page load.  

![image](https://cloud.githubusercontent.com/assets/281070/10563838/1913e790-7568-11e5-942d-5479dd4b5600.png)

**Comment by TheSharpieOne** [comment]
This is due to bootstrap. bootstrap will position the popover to be inside the viewport when triggered.  The workaround is to position the popover on the top or bottom of the element it is attached to.
This workaround was done for 1.x in #223 popover docs cleanup
