### ISSUE TITLE
upgrade Select2 to v4

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#157]

**Comment by JamieCrisman** [comment]
complete?

**Comment by robmcguinness** [comment]
i think so.  some style updates in v2 of UIKit that are WIP
- https://github.com/Availity/availity-uikit/commit/2785ef52ee07186739f9c5526009f360799d38ba
- https://github.com/Availity/availity-uikit/commit/068ed1317d39e8eb0482e68dfe4920925ba34d7d
