### ISSUE TITLE
Not able to do dependent validation

### ISSUE THREAD

**Issue by Sepiac** [Availity/availity-angular#158]
Need the ability to validate based on the value of other fields. For instance, making sure that a start date cannot be set to a time after an end date, and vice versa.

**Comment by TheSharpieOne** [comment]
You can currently do this in the 1.x branch. Grab the formControl from the element passed to the validate method and using that you can get any other field in the form using the field's name value as the key.

Here is a quick example of how to make sure a field's value is greater than other field's value. When the values are dates, this would match your use-case.
```
//...

function validate (value, rule, element) {
  var formCtrl = element && element.controller('form');
  if(!formCtrl) {
    $log.warn('No formController found');
    return;
  }

  var otherField = formCtrl[rule.otherFieldName]; // the rule would indicate which field to be dynamic
  return value && value >= otherField.$modelValue;
}

//...

return {
  validate: validate,
  name: 'greaterThanField'
};

//...
```

**Comment by robmcguinness** [comment]
`v2` integrates with Angular 1.6 validation as well as the workaround mentioned above
