### ISSUE TITLE
Gracefully fail when 3rd party libs are missing

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#166]
This basically means that if a 3rd party lib like [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) isn't loaded then `avDatepicker` should gracefully fail.  This would allow developers to cherry pick which modules they want to use and not get forced to load libraries that are unused.

**Comment by KaseyPowers** [comment]
So for this example, if bootstrap-datepicker is not loaded, avDatepicker will throw a custom error if something attempts to use it, indicating the missing libraries to be added?

**Comment by robmcguinness** [comment]
yes

**Comment by robmcguinness** [comment]
We already inform Webpack to treat those 3rd party libraries as external.  One thing to watch out for is using `import` vs `require` when dealing with conditionally included libs.
