### ISSUE TITLE
Add NPI Validator

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#171]

**Comment by JamieCrisman** [comment]
This is probably (hopefully) already the plan, but...

NPIs use the Luhn Algorithm. I think some approaches for validation used a database to check the NPI, but this would be a simple algorithmic way to check on the front end. And the backend could check further if needed on submission.

https://en.wikipedia.org/wiki/National_Provider_Identifier (ctrl+f luhn and it'll talk about NPI validation using Luhn)

https://en.wikipedia.org/wiki/Luhn_algorithm

**Comment by robmcguinness** [comment]
@JamieCrisman right on. I basically ported over some work done by @dnoler

**Comment by dnoler** [comment]
@robmcguinness @JamieCrisman Port looks good to me.
