### ISSUE TITLE
AvLogger supplant method is mangling angular digest errors

### ISSUE THREAD

**Issue by andrewaramsay** [Availity/availity-angular#175]
When I get an error about the digest hitting it's limit, the error message actually written to the console is extremely cryptic.  For example:

    TypeError: Cannot read property '"msg": "fn: regularInterceptedExpression","newVal":26' of undefined.

This seems to be some confusion in the `supplant` method of `AvLogger`, where the `supplantData` object is undefined, and the angular error message contained lots of `{` and `}` characters, so the regex is matching.

A hack fix is to simply check for `!o` at the top of `supplant` on line 28 and return `str` instead of running the regex, but I don't think this is the real fix to the problem, so I'm opening an issue instead of submitting a PR.  I'll see if I can find some time to understand the problem better and come up with a proper fix.

I believe I have seen this with other internal angular errors as well, such as when ng-repeat fails due to duplicate objects.

**Comment by robmcguinness** [comment]
If you could look into it a little deeper then that would be great.  We could maybe switch to `$interpolate` since it's a better string based template language.

I was never really satisfied with `AvLogger` :koala:

**Comment by andrewaramsay** [comment]
Submitted a pull request to fix this.  I ended up deciding I did like the solution that I referred to as a "hack" above.  I didn't want to go down the route of changing the templating approach, since it would be a breaking change to anyone currently using the supplanting feature.  That may be a good direction to take it for v2 though.

**Comment by robmcguinness** [comment]
ok sounds good.  i completely removed the supplant functionality in `v2`. Check out the implementation when you can https://github.com/Availity/availity-angular/blob/feature/v2/lib/core/logger/logger.js
