### ISSUE TITLE
AvAnalytics should be split into parent and child directives

### ISSUE THREAD

**Issue by Riggd** [Availity/availity-angular#176]
Currently on every element that needs to be tracked we have to clog the DOM with repetitive attributes. If we break the directive into avAnalyticsOn and avAnalyticsLabel, we only need to initialize avAnalyticsOn and avAnalyticsCategory on the main page container and each element will then just have the single avAnalyticsLabel on their tag.

**Current Markup**
```
<div>
  <ul>
    <li av-analytics-on='click' av-analytics-category='page1' av-analytics-label='label 1'>Label 1</li>
    <li av-analytics-on='click' av-analytics-category='page1' av-analytics-label='label 2'>Label 2</li>
  </ul>
</div>
```

**Proposed Change**
```
<div av-analytics-on='click' av-analytics-category='page1'>
  <ul>
    <li av-analytics-label='label 1'>Label 1</li>
    <li av-analytics-label='label 2'>Label 2</li>
  </ul>
</div>
```

**Comment by robmcguinness** [comment]
interesting.  we do something very similar for the Angular validation framework.

**Comment by bobbennett** [comment]
Having the -on attribute on a container seems a bit odd since you are tracking individual actions. I agree the category can be brought up to a parent level though. 

Maybe we can just have a default event? Add it to the config and default it to click. What do you guys think?

**Comment by robmcguinness** [comment]
we already default `click`

https://github.com/Availity/availity-angular/blob/2419160d92a731b230857096be54b6e30c629409/lib/ui/analytics/analytics.js#L42

**Comment by bobbennett** [comment]
I should have looked first. Do you agree with leaving the -on attribute at the "child" level and not a parent?

**Comment by robmcguinness** [comment]
@bobbennett sounds good to me

**Comment by derekonay** [comment]
Sounds good, I'll use this approach!
