### ISSUE TITLE
NPI validator does not handle optional NPI fields properly.

### ISSUE THREAD

**Issue by Sepiac** [Availity/availity-angular#184]
The default NPI validator assumes that every NPI field is required, but that is not always the case.

**Comment by robmcguinness** [comment]
I"m not sure if I understand.  The npi validator is added to a field that not required but the npi validator is still firing? 

Here is the spec that test for the condition above.  Can you review and see if I am understanding correctly?

https://github.com/Availity/availity-angular/blob/master/lib/core/validation/validators/tests/validator-npi-spec.js#L13

**Comment by Sepiac** [comment]
I'm thinking that it might be better general solution to allow blank npis, and do the empty input check with the required validator. I ran into a use case where we have an npi field that is not required, but I can't use the default npi validator because it won't allow blank input through.

**Comment by dnoler** [comment]
@robmcguinness I see the issue. The test case needs to be reversed. If the input is empty, undefined, or null, the validator SHOULD validate. It should not assume the input is required.

**Comment by robmcguinness** [comment]
@dnoler yeah i read the tests wrong.  this needs to be patched.
