### ISSUE TITLE
Select2 Does not validate on 'blur'

### ISSUE THREAD

**Issue by nickolaswilson** [Availity/availity-angular#194]
select id="physicianCredential" data-av-dropdown data-allow-clear="true" data-placeholder="Select One" class="form-control select2" ng-model="rafs.raf.attestation.physicianCredential" ng-options="option for option in rafs.constants.DROP_DOWNS.physicianCredential" av-val-field="physicianCredential"

The above won't validate the field on blur like the rest of the input fields or if select2 isn't present. It seems the propagation of the blur event isn't hitting the validator. It only validates if the value is changed.

**Comment by JamieCrisman** [comment]
force a validation at this point?

https://github.com/Availity/availity-angular/blob/master/lib/ui/dropdown/dropdown.js#L409

**Comment by robmcguinness** [comment]
@JamieCrisman possibly if the `blur` event is registered as the trigger for validation
