### ISSUE TITLE
code markdown sections not displaying characters correctly

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-angular#208]
Notably ' becomes &apos;

can be seen in the Event Tracking html code at http://demo.availity.com/public/apps/availity-angular/core.html#/Analytics

**Comment by derekonay** [comment]
Just wanted to chime in. I attempted to escape the characters and also ascii characters as a work around, but neither resolved the issue.

**Comment by robmcguinness** [comment]
try http://availity.github.io/availity-uikit/v2.0.0-beta.4/pages/components/#basic

**Comment by KaseyPowers** [comment]
It seems to be working, although I am not crazy about the horizontal
scrollbar.

On Tue, Mar 22, 2016 at 1:38 PM, robert mcguinness <notifications@github.com

**Comment by robmcguinness** [comment]
feel free to back-port the fix to `v1`
