### ISSUE TITLE
Helper function for analytics

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#211]
Sometimes a directive isn't sufficient to capture complex analytics.  A helper function that sends the appropriate analytics attributes would be useful,

**Comment by KaseyPowers** [comment]
Could you provide more details?
For custom analytics I have used the avAnalytics.trackEvent function.

**Comment by robmcguinness** [comment]
Below is the `onEvent` handler from the directive.  Notice that it defaults the level to `info`.  Maybe all we need is some sensible defaults in `avAnalytics.trackEvent` and we have a good helper function.
```js
 onEvent(event, element, options) {

    const properties = angular.extend(
      {
        level: 'info',
        label: element.text()
      },
      {
        event: event.type
      },
      options
    );

    if (this.av.avAnalyticsUtils.isExternalLink(properties)) {
      event.preventDefault();
      event.stopPropagation();
    }

    const promise = this.av.avAnalytics.trackEvent(properties);

  }
```

**Comment by KaseyPowers** [comment]
Default values or validation make sense, but not sure what they should be other than level for splunk, which is implemented in the service.
```javascript
  properties.url = $location.$$absUrl || 'N/A';
  properties.level = properties.level || 'info';
```

**Comment by robmcguinness** [comment]
we should be good then.
