### ISSUE TITLE
$target.offset is undefined for hidden elements

### ISSUE THREAD

**Issue by solingeravaility** [Availity/availity-angular#243]
I'm on version 1.10.1

In avValBootstrapAdapter the scroll function has a timeout function which is throwing the following exception: `TypeError: Cannot read property 'top' of undefined`

This occurs in the case where a form is submitted with a hidden element.  It appears that `$target.offset()` is returning undefined for a hidden element.  The line that is causing the exception is the following:

[`$('body, html').animate({scrollTop: $target.offset().top - offset}, 'fast');`](https://github.com/Availity/availity-angular/blob/v1.10.1/lib/ui/validation/adapter-bootstrap.js#L89)

**Comment by KaseyPowers** [comment]
This appears to have been fixed for v1 and v2.
