### ISSUE TITLE
Add configuration flag to use http override methods when wanting to query with post (V1 and V2)

### ISSUE THREAD

**Issue by AvMeetaoberoi** [Availity/availity-angular#256]
Please add the ability in AvApiResource to go a POST with an X-HTTP-Method-Override':'GET'. This is needed for GT request that contain sensitive PHI information.

**Comment by robmcguinness** [comment]
@KaseyPowers,

The goal is to always `POST` but add the appropriate http override header so that the server can read it and execute the correct method.  

**Create a helper function**  
```js
avResource
  .overrideGet({/* options */});

// or maybe this API reads better?
avResource
   .postGet({/* options */});
```

Internally the function would just call `.create` with `X-HTTP-Method-Override:'GET'` properly set.

**Comment by KaseyPowers** [comment]
my initial thoughts would be to have a before* function for each type of call to modify the config, then change the current beforeCreate and beforeUpdate names to reflect that it modifies the data. 
Then a user could just add something like this to their resource

```javascript
beforeCreate(config) {
  config.headers['X-HTTP-Method-Override] = 'GET';
  return config;
}
```

This would be more flexible?
