### ISSUE TITLE
avDropdown options allowClear does not work

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/availity-angular#277]
avDropdown options allowClear does not work. See the examples: http://availity.github.io/availity-angular/pages/ui/#dropdowns many have `allowClear: true` yet the little "x" does not appear and the dropdown's cannot be cleared.

**Comment by robmcguinness** [comment]
Fixed with https://github.com/Availity/availity-angular/commit/10d51d9b34376e36da404f4e614d3d63e36b81e2
