### ISSUE TITLE
avDropdown options placeholder does not work

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/availity-angular#278]
avDropdown options placeholder does not work. See the examples: http://availity.github.io/availity-angular/pages/ui/#dropdowns many have a placeholder set yet nothing appearswhen the dropdowns are empty.

**Comment by KaseyPowers** [comment]
For the demo page at least it looks like the problem is that they need an empty option for the placeholder to populate. 
```
Note that because browsers assume the first option element is selected in non-multi-value select boxes an empty first option element must be provided (<option></option>) for the placeholder to work.
```

**Comment by TheSharpieOne** [comment]
That worked for some, but not all. I think defaulting the initial values to `null` also plays a role.
