### ISSUE TITLE
avDropdown - does not reflect changes to ngModel with query option

### ISSUE THREAD

**Issue by jselden** [Availity/availity-angular#286]
When using dynamic query option if another process changes ngModel it was not being represented in select2.  Example:
Had speciality dropdown for provider but when set provider.speciality it was not display in input when we change value from express entry.
Simliarly on demo the to query examples are using same selectedPhoto model.  Prior to change a change in one was not being represented in other.  After fix the keep in sync.

**Comment by robmcguinness** [comment]
I believe this was closed.
