### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#298]
Similar to other Availity projects:
- https://github.com/Availity/availity-workflow/blob/master/CHANGELOG.md
- https://github.com/Availity/availity-workflow/blob/master/package.json#L5-L7
- https://github.com/Availity/availity-workflow/blob/master/package.json#L9-L10

**Comment by christieb7007** [comment]
changlog/release script added with https://github.com/Availity/availity-angular/pull/306
