### ISSUE TITLE
avDropdown always triggers ngChange twice

### ISSUE THREAD

**Issue by Sepiac** [Availity/availity-angular#74]
On the first trigger of ngChange, the expected result is returned. On the second trigger, an index object is returned.

**Comment by robmcguinness** [comment]
if you could provide an example?

**Comment by Sepiac** [comment]
Clone this repo and run it: https://git.availity.com/users/drussell/repos/av-dropdown-demo/browse

**Comment by Sepiac** [comment]
Clone this repo and run it: https://github.com/Sepiac/av-dropdown-demo

**Comment by robmcguinness** [comment]
Please use https://github.com/Availity/availity-angular/releases/tag/v0.12.0 which was fixed https://github.com/Availity/availity-angular/commit/0d57cc980120b1f3ef48aa779651a4820c08edde
