### ISSUE TITLE
Add directive to prettify radio buttons and checkboxes

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-angular#79]

**Comment by bobbennett** [comment]
Should this be optional? Devs don't have to add a directive to their inputs, but LESS would force the matter

**Comment by robmcguinness** [comment]
It could still be a directive that is automatically attached to the radio or checkbox element...the developer would not need to code anything.  something like https://code.angularjs.org/1.2.27/docs/api/ng/directive/input

**Comment by bobbennett** [comment]
Yep. Didn't think about using it that way.

**Comment by robmcguinness** [comment]
this is handled by CSS now
