### ISSUE TITLE
date picker doesn't appear to be binding to the model correctly

### ISSUE THREAD

**Issue by danielspangler** [Availity/availity-angular#8]
I'm using the snippet below to define the date picker.  The binding appears to fail in both directions.  If I set inquiry.dateOfService equal to "new Date()", I get the error in the bottom of the issue on page load.  If I set that to null, use the date picker to select a date, then inspect the value of inquiry.dateOfService then the value is equal to an empty string.

```html
<div class='input-group date' data-av-datepicker data-min-date="inquiry.minDate" data-max-date="inquiry.maxDate">
    <input type="text" class="form-control" id="withIcon" data-ng-model="inquiry.dateOfService" />
     <span class="input-group-addon">
         <span class="icon icon-calendar"></span>
     </span>
</div>
```

 TypeError: Cannot read property 'date' of undefined
    at availity.ui.controller.setValue (availity-angular-ui.js:1098)
    at availity.ui.directive.link.ngModel.$render (availity-angular-ui.js:1183)
    at Object.ngModelWatch (angular.js:17899)
    at Scope.$get.Scope.$digest (angular.js:12642)
    at angular.js:9942
    at angular.js:4559
    at forEach (angular.js:325)
    at fireUrlChange (angular.js:4558)
    at jQuery.event.dispatch (jquery.js:4665)
    at jQuery.event.add.elemData.handle (jquery.js:4333)

**Comment by robmcguinness** [comment]
Thanks for reporting this issue.  Let me see what I find.

**Comment by robmcguinness** [comment]
Let me know when you have tried the [v0.4.3](https://github.com/Availity/availity-angular/releases/tag/v0.4.3) to see if it fixes the problem

**Comment by robmcguinness** [comment]
I believe this issue has been resolved after the datepicker was switched.   Please reopen if needed.
